apply plugin: 'com.android.application'

android {
    compileSdkVersion rootProject.ext.compileSdk

    testBuildType "debug"

    signingConfigs {
        myConfig {
            storeFile file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildFeatures.buildConfig = true

    defaultConfig {
        applicationId "com.github.h6ah4i.numbermorphing.example"
        versionCode 12
        versionName "2.0"
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk

        testInstrumentationRunner "android.test.InstrumentationTestRunner"
        testHandleProfiling false

        buildConfigField "boolean", "EXTRA_LOGS", "false"
        resourceConfigurations += ['en']
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-DEBUG"
            signingConfig signingConfigs.myConfig

            buildConfigField "boolean", "EXTRA_LOGS", "true"

            minifyEnabled true
            shrinkResources true
        }
    }

    namespace 'com.github.h6ah4i.numbermorphing.example'
    androidResources {
        ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~'
        noCompress 'txt'
    }
    lint {
        htmlOutput file('lint-report.html')
        htmlReport true
        lintConfig file('default-lint.xml')
        showAll true
        textOutput file('stdout')
        textReport true
        xmlOutput file('lint-report.xml')
        xmlReport true
    }
}

dependencies {
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation project(':library')
}